(* Generated by scripts/hyperball-reference-constants.py.
   Inputs are independently compiled from the pinned C reference.
   C evaluator: compiler selected by CC (default cc); version reported by generator.
   C flags: -O2 -std=c11 -Wall -Wextra; HAETAE_CONFIG_MODE=HAETAE_MODE2/3/5.
   Input: HAETAE-1.2.0/reference_implementation/include/common.h
   SHA-256: 72c062d86e4c6b900fb1df18cfc892526d3ebec17dc2b417db4a76a2531fe5e1
   Input: HAETAE-1.2.0/reference_implementation/include/config.h
   SHA-256: 4a9c0d19d428ff0fa2e4163fa5641a966d3a1fa992f57e2a8c71fe5e2866110b
   Input: HAETAE-1.2.0/reference_implementation/include/params.h
   SHA-256: cba72f62fab3f53b4165510afecd1e3d9ebee63cd5e875d2a3e51437db3a5726
   Input: HAETAE-1.2.0/reference_implementation/include/fixpoint.h
   SHA-256: 6a54bd1761f37c29dbf7f476d17d27ee42b836f084e1216aefad60b891833465
   Input: HAETAE-1.2.0/reference_implementation/src/fixpoint.c
   SHA-256: ff6896a4bd78151ea95b40f90bd6944c4cf3d5005dd101cfc31247a0df611b13
   Input: HAETAE-1.2.0/reference_implementation/src/polyfix.c
   SHA-256: 2859b37496fc26084ee775893ef88cae4c15f470db1da41b58d6d73480483c9e
   Scale/bound expressions retain the C floating-point casts.
   Defaults outside modes 2/3/5 are zero; wrapper theorems restrict modes. *)

require import AllCore.
from Jasmin require import JModel_x86.

op hb_ref_l (mode : int) : int =
  if mode = 2 then 4
  else if mode = 3 then 6
  else if mode = 5 then 7
  else 0.

op hb_ref_k (mode : int) : int =
  if mode = 2 then 2
  else if mode = 3 then 3
  else if mode = 5 then 4
  else 0.

op hb_ref_scale (mode : int) : W64.t =
  if mode = 2 then W64.of_int 2643021496320
  else if mode = 3 then W64.of_int 4916390789120
  else if mode = 5 then W64.of_int 5997831421952
  else W64.zero.

op hb_ref_bound (mode : int) : W64.t =
  if mode = 2 then W64.of_int 6505809026482176
  else if mode = 3 then W64.of_int 22510896139993088
  else if mode = 5 then W64.of_int 33503371683954688
  else W64.zero.

op hb_ref_cube (mode : int) : W64.t * W64.t =
  if mode = 2 then (W64.of_int 130843895063578, W64.of_int 4450)
  else if mode = 3 then (W64.of_int 28764298784360, W64.of_int 2424)
  else if mode = 5 then (W64.of_int 123213818923277, W64.of_int 1794)
  else (W64.zero, W64.zero).

op hb_ref_three (mode : int) : W64.t * W64.t =
  if mode = 2 then (W64.of_int 115690877850491, W64.of_int 10267222)
  else if mode = 3 then (W64.of_int 135042716239155, W64.of_int 8384969)
  else if mode = 5 then (W64.of_int 96105673977137, W64.of_int 7585088)
  else (W64.zero, W64.zero).
