#!/usr/bin/env python3
"""Generate exact integer Bernstein certificates for the exponential grid.

The coefficients are read from the pinned C expression.  Fraction arithmetic
constructs six degree-ten certificates; EasyCrypt separately checks their
identities, signs, analytic meaning, and connection to the actual evaluator.
This script does not evaluate exp or assume a floating-point error estimate.
"""
import argparse
from fractions import Fraction
import hashlib
import importlib.util
import json
from math import comb
from pathlib import Path


PROJECT = Path(__file__).resolve().parents[1]
REFERENCE = PROJECT.parent / "HAETAE-1.2.0/reference_implementation/src/sampler.c"
M = 1 << 48
K = 24
CELLS = 3
DEGREE = 10
DENOMINATOR = M**10 * 9**10 * 2520


def coefficients(reference: Path) -> list[int]:
    spec = importlib.util.spec_from_file_location(
        "haetae_reference_constants", PROJECT / "scripts/reference-constants.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.parse_coefficients(reference.read_text())


def affine(poly: list[Fraction], start: Fraction, width: Fraction) -> list[Fraction]:
    """Power coefficients of poly(start + width*t)."""
    return [sum((poly[j] * comb(j, k) * start**(j-k) * width**k
                 for j in range(k, DEGREE + 1)), Fraction(0))
            for k in range(DEGREE + 1)]


def to_bernstein(poly: list[Fraction]) -> list[Fraction]:
    return [sum((poly[k] * Fraction(comb(i, k), comb(DEGREE, k))
                 for k in range(i + 1)), Fraction(0))
            for i in range(DEGREE + 1)]


def to_power(controls: list[int]) -> list[int]:
    return [comb(DEGREE, k) * sum((-1)**(k-i) * comb(k, i) * controls[i]
                                  for i in range(k + 1))
            for k in range(DEGREE + 1)]


def integer_numerators(values: list[Fraction]) -> list[int]:
    scaled = [v * DENOMINATOR for v in values]
    if any(v.denominator != 1 for v in scaled):
        raise ValueError("certificate denominator does not clear all fractions")
    return [v.numerator for v in scaled]


def certificate(reference: Path) -> dict:
    descending = coefficients(reference)
    if len(descending) != DEGREE + 1:
        raise ValueError("expected the pinned degree-ten Horner evaluator")
    # g=M*P has the actual integer coefficients in ascending power order.
    g = [Fraction(c) for c in reversed(descending)]
    shifted = affine(g, Fraction(1, M), Fraction(1))
    # These are M times the two cross-multiplied recurrence residuals.
    residuals = {
        "upper": [(M+1)*shifted[i] - M*g[i] for i in range(DEGREE+1)],
        "lower": [(M-1)*g[i] - M*shifted[i] for i in range(DEGREE+1)],
    }
    rows = []
    for name, poly in residuals.items():
        poly[0] += K
        for cell in range(CELLS):
            local = affine(poly, Fraction(2*cell, 9), Fraction(2, 9))
            power = integer_numerators(local)
            bernstein = integer_numerators(to_bernstein(local))
            if power != to_power(bernstein) or not all(v >= 0 for v in bernstein):
                raise ValueError(f"invalid {name} certificate on cell {cell}")
            rows.append({"kind": name, "cell": cell, "power": power, "bernstein": bernstein})
    return {"coefficients": descending, "rows": rows}


def integer_literal(value: int) -> str:
    return str(value) if value >= 0 else f"({value})"


def integer_list(name: str, values: list[int]) -> str:
    return f"op [opaque] {name} : int list =\n  [" + ";\n   ".join(map(integer_literal, values)) + "].\n"


def generate(reference: Path, data: dict) -> str:
    result = [
        "(* Generated by scripts/approx-exp-certificate.py using exact fractions.\n"
        "   Official coefficient correspondence: specification 260904, section 5.1.1, Listing 1.\n"
        "   No external real-exponential evaluation is used as a proof oracle.\n"
        f"   Compared C source SHA-256: {hashlib.sha256(reference.read_bytes()).hexdigest()} *)\n",
        "require import AllCore List.\n",
        f"op aec_scale : int = {M}.\n"
        f"op aec_error_units : int = {K}.\n"
        f"op aec_domain_limit : int = {2*M//3}.\n"
        f"op aec_denominator : int = {DENOMINATOR}.\n",
        integer_list("aec_coefficients", data["coefficients"]),
    ]
    for row in data["rows"]:
        stem = f"aec_{row['kind']}_{row['cell']}"
        result.append(integer_list(stem + "_power", row["power"]))
        result.append(integer_list(stem + "_bernstein", row["bernstein"]))
    return "\n".join(result)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=REFERENCE)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--summary", type=Path)
    args = parser.parse_args()
    data = certificate(args.reference)
    args.output.write_text(generate(args.reference, data))
    if args.summary:
        args.summary.write_text(json.dumps({
            "method": "exact integer Bernstein certificate; analytic and implementation connections require EasyCrypt proofs",
            "domain": "0 <= x/2^48 <= 2/3", "cells": 3, "polynomials": 6,
            "controls": 66, "denominator": str(DENOMINATOR),
            "polynomial_error_units": K, "scale": M,
            "intended_horner_error_units": 3, "intended_total_error": "<32/2^48=2^-43",
            "minimum_control": str(Fraction(min(v for r in data['rows'] for v in r['bernstein']), DENOMINATOR)),
            "formal_verification_result": "pending",
            "one_sided_ceiling_or_renyi_claim": False,
        }, indent=2) + "\n")
    print("Generated six exact Bernstein certificates; all66 controls nonnegative; analytic proof required")


if __name__ == "__main__":
    main()
