#!/usr/bin/env python3
"""Emit integer certificates for the sigma=16 nonnegative Gaussian CDT.

Only integer arithmetic constructs the enclosures.  Their analytic soundness
and the finite certificate checks are proved separately in EasyCrypt; this
generator is not an oracle for exp or for a claimed Gaussian distribution.
The mathematical target comes from specification 260904 section 5.1.1 and
its reference [21], Algorithm 12.  The C table is only the object compared to
that target.  No Jasmin/extracted-program file supplies the target definition.
"""

import argparse
from fractions import Fraction
import hashlib
import importlib.util
import json
from pathlib import Path


PROJECT = Path(__file__).resolve().parents[1]
REFERENCE = PROJECT.parent / "HAETAE-1.2.0/reference_implementation/src/sampler.c"
SCALE = 1 << 320
SEED_DENOMINATOR = 1 << 137
SQUARINGS = 128
CUTOFF = 256
INPUT_SIZE = 1 << 83
PROBABILITY_SCALE = 1 << 128


def ceildiv(n: int, d: int) -> int:
    if n < 0 or d <= 0:
        raise ValueError("certificate division requires n >= 0 and d > 0")
    return (n + d - 1) // d


def multiply(a: tuple[int, int], b: tuple[int, int]) -> tuple[int, int]:
    return a[0] * b[0] // SCALE, ceildiv(a[1] * b[1], SCALE)


def reference_thresholds(reference: Path) -> list[int]:
    location = PROJECT / "scripts/reference-constants.py"
    spec = importlib.util.spec_from_file_location("haetae_reference_constants", location)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    source = reference.read_text()
    high = module.parse_array(source, "CDT83_HI", 32, 76)
    low = module.parse_array(source, "CDT83_LO", 64, 166)
    high += [(1 << 19) - 1] * (len(low) - len(high))
    table = [(h << 64) + l for h, l in zip(high, low)]
    if table != sorted(table) or not all(0 <= t < INPUT_SIZE for t in table):
        raise ValueError("invalid reference CDT thresholds")
    return table


def certificate(reference: Path) -> dict:
    # 1 - 1/d <= exp(-1/d) <= d/(d+1), followed by 128 squarings.
    assert SCALE % SEED_DENOMINATOR == 0
    first = (
        SCALE - SCALE // SEED_DENOMINATOR,
        ceildiv(SCALE * SEED_DENOMINATOR, SEED_DENOMINATOR + 1),
    )
    squaring = [first]
    for _ in range(SQUARINGS):
        squaring.append(multiply(squaring[-1], squaring[-1]))
    q = squaring[-1]
    q2 = multiply(q, q)
    # w_k = q^(k*k), r_k = q^(2*k+1).  These finite recurrences avoid
    # transcendental evaluation and retain outward rounding at every step.
    weights = [((SCALE, SCALE), q)]
    for _ in range(CUTOFF):
        w, ratio = weights[-1]
        weights.append((multiply(w, ratio), multiply(ratio, q2)))
    assert 0 <= weights[-1][1][1] < SCALE
    tail_weight = ceildiv(SCALE * weights[-1][0][1], SCALE - weights[-1][1][1])
    normalizer = (
        sum(w[0] for w, _ in weights[:CUTOFF]),
        sum(w[1] for w, _ in weights[:CUTOFF]) + tail_weight,
    )
    assert 0 < normalizer[0] <= normalizer[1]

    thresholds = reference_thresholds(reference)
    # The implementation uses T < U, so its CDF cut points are T+1.
    endpoints = [0] + [t + 1 for t in thresholds] + [INPUT_SIZE]
    counts = [b - a for a, b in zip(endpoints, endpoints[1:])]
    counts += [0] * (CUTOFF - len(counts))
    assert len(counts) == CUTOFF and sum(counts) == INPUT_SIZE
    assert PROBABILITY_SCALE % INPUT_SIZE == 0
    lift = PROBABILITY_SCALE // INPUT_SIZE

    pmf = [
        (PROBABILITY_SCALE * w[0] // normalizer[1],
         ceildiv(PROBABILITY_SCALE * w[1], normalizer[0]))
        for w, _ in weights[:CUTOFF]
    ]
    point_errors = [
        max(abs(c * lift - bounds[0]), abs(c * lift - bounds[1]))
        for c, bounds in zip(counts, pmf)
    ]
    tail_probability = ceildiv(PROBABILITY_SCALE * tail_weight, normalizer[0])
    variation_numerator = sum(point_errors) + tail_probability
    assert INPUT_SIZE * variation_numerator < 64 * PROBABILITY_SCALE

    return {
        "squaring": squaring, "weights": weights, "normalizer": normalizer,
        "tail_weight": tail_weight, "thresholds": thresholds, "counts": counts,
        "pmf": pmf, "point_errors": point_errors, "tail_probability": tail_probability,
        "variation_numerator": variation_numerator,
    }


def literal(value) -> str:
    if isinstance(value, tuple):
        return "(" + ", ".join(literal(part) for part in value) + ")"
    return str(value) if value >= 0 else f"({value})"


def ec_list(name: str, datatype: str, values: list) -> str:
    return f"op [opaque] {name} : {datatype} list =\n  [" + ";\n   ".join(map(literal, values)) + "].\n"


def generate(reference: Path, data: dict) -> str:
    output = [
        "(* Generated by scripts/gaussian-cdt-certificate.py.\n"
        "   Target: rho(k)=exp(-k^2/512), k>=0, normalized over all nonnegative integers.\n"
        "   Official source: specification 260904 section 5.1.1 and reference [21].\n"
        "   The analytic certificate checker is independent of the implementation table.\n"
        f"   Compared C input SHA-256: {hashlib.sha256(reference.read_bytes()).hexdigest()} *)\n",
        "require import AllCore List ExpIntervalSpec.\n",
        f"op gi_scale : int = {SCALE}.\n"
        f"op gi_seed_denominator : int = {SEED_DENOMINATOR}.\n"
        f"op gi_squarings : int = {SQUARINGS}.\n"
        f"op gi_cutoff : int = {CUTOFF}.\n"
        f"op gi_input_size : int = {INPUT_SIZE}.\n"
        f"op gi_probability_scale : int = {PROBABILITY_SCALE}.\n",
        ec_list("gi_squaring_chain", "ei_interval", data["squaring"]),
        ec_list("gi_weight_chain", "ei_weight_state", data["weights"]),
        f"op gi_normalizer_bounds : ei_interval = {literal(data['normalizer'])}.\n"
        f"op gi_tail_weight_upper : int = {data['tail_weight']}.\n"
        f"op gi_tail_probability_upper : int = {data['tail_probability']}.\n",
        ec_list("gi_thresholds", "int", data["thresholds"]),
        ec_list("gi_probability_counts", "int", data["counts"]),
        ec_list("gi_pmf_bounds", "ei_interval", data["pmf"]),
        ec_list("gi_point_error_bounds", "int", data["point_errors"]),
    ]
    return "\n".join(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=REFERENCE)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--summary", type=Path)
    args = parser.parse_args()
    data = certificate(args.reference)
    args.output.write_text(generate(args.reference, data))
    if args.summary:
        summary = {
            "method": "outward integer interval certificate; requires separate EasyCrypt soundness proof",
            "target": "exp(-k^2/512) / sum_{j>=0} exp(-j^2/512), k>=0",
            "scale_bits": 320, "initial_denominator_bits": 137, "squarings": 128,
            "normalization_cutoff": CUTOFF, "probability_scale_bits": 128,
            "statistical_distance_upper": str(Fraction(data["variation_numerator"], 2 * PROBABILITY_SCALE)),
            "statistical_distance_target": "32 / 2^83",
            "actual_shake_uniformity_claimed": False,
            "formal_verification_result": "pending",
        }
        args.summary.write_text(json.dumps(summary, indent=2) + "\n")
    print("Generated outward-rounded CDT/Gaussian certificate; numeric checks pass; analytic proof required")


if __name__ == "__main__":
    main()
