#!/usr/bin/env python3
"""Generate Hyperball constants by compiling the pinned C reference.

The Jasmin source and EasyCrypt extraction are not inputs. C evaluates the
floating-point expressions and their uint64_t casts before Python formats the
result. Generated provenance uses repository-relative paths, without temporary
directories, timestamps, or installation-specific compiler paths.
"""
import argparse
import hashlib
import os
from pathlib import Path
import shlex
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "HAETAE-1.2.0/reference_implementation"
INPUTS = (
    "include/common.h", "include/config.h", "include/params.h",
    "include/fixpoint.h", "src/fixpoint.c", "src/polyfix.c",
)
MODES = (2, 3, 5)
FLAGS = ("-O2", "-std=c11", "-Wall", "-Wextra")

# fixpoint.c supplies the actual mode-specific start_cube/start_times_threehalves
# initializers. The other expressions are those used in src/polyfix.c:269-285.
EMITTER = r'''#include <inttypes.h>
#include <stdio.h>
#include "fixpoint.c"

int main(void) {
  const uint64_t values[8] = {
    HAETAE_L,
    HAETAE_K,
    (uint64_t)(HAETAE_B0 * HAETAE_LN + HAETAE_SQNM / 2) << (28 - 13),
    HAETAE_B0SQ * HAETAE_LN * HAETAE_LN,
    start_cube.limb48[0], start_cube.limb48[1],
    start_times_threehalves.limb48[0], start_times_threehalves.limb48[1]
  };
  for (unsigned i = 0; i < 8; ++i)
    printf("%" PRIu64 "%c", values[i], i == 7 ? '\n' : ' ');
  puts(__VERSION__);
  return 0;
}
'''


def reference_values(reference: Path) -> tuple[dict[int, tuple[int, ...]], str]:
    compiler = shlex.split(os.environ.get("CC", "cc"))
    if not compiler:
        raise ValueError("CC must name a C compiler")
    values, versions = {}, set()
    with tempfile.TemporaryDirectory(prefix="haetae120-hyperball-constants-") as folder:
        temporary = Path(folder)
        source = temporary / "constants.c"
        source.write_text(EMITTER, encoding="utf-8")
        for mode in MODES:
            executable = temporary / f"mode{mode}"
            subprocess.run([
                *compiler, *FLAGS,
                f"-DHAETAE_CONFIG_MODE=HAETAE_MODE{mode}",
                "-I", str(reference / "include"), "-I", str(reference / "src"),
                str(source), "-o", str(executable),
            ], check=True)
            output = subprocess.run(
                [str(executable)], check=True, capture_output=True, text=True,
            ).stdout.splitlines()
            if len(output) != 2:
                raise ValueError(f"unexpected C emitter output for mode {mode}")
            row = tuple(int(value) for value in output[0].split())
            if len(row) != 8 or any(not 0 <= value < 1 << 64 for value in row):
                raise ValueError(f"invalid C constants for mode {mode}")
            values[mode] = row
            versions.add(output[1])
    if len(versions) != 1:
        raise ValueError("C compiler version changed between mode evaluations")
    return values, versions.pop()


def generate(reference: Path = REFERENCE) -> str:
    reference = reference.resolve()
    # Read and hash before compiling; reject concurrent changes to the inputs.
    inputs = {name: (reference / name).read_bytes() for name in INPUTS}
    values, compiler_version = reference_values(reference)
    print(f"C compiler __VERSION__: {compiler_version}", file=sys.stderr)
    if any((reference / name).read_bytes() != data for name, data in inputs.items()):
        raise ValueError("C reference changed while generating constants")
    provenance = [
        "(* Generated by scripts/hyperball-reference-constants.py.",
        "   Inputs are independently compiled from the pinned C reference.",
        "   C evaluator: compiler selected by CC (default cc); version reported by generator.",
        f"   C flags: {' '.join(FLAGS)}; HAETAE_CONFIG_MODE=HAETAE_MODE2/3/5.",
    ]
    for name, data in inputs.items():
        provenance.extend([
            f"   Input: HAETAE-1.2.0/reference_implementation/{name}",
            f"   SHA-256: {hashlib.sha256(data).hexdigest()}",
        ])
    provenance.extend([
        "   Scale/bound expressions retain the C floating-point casts.",
        "   Defaults outside modes 2/3/5 are zero; wrapper theorems restrict modes. *)",
    ])
    output = ["\n".join(provenance),
              "require import AllCore.\nfrom Jasmin require import JModel_x86."]
    operations = (
        ("hb_ref_l", "int", (0,)),
        ("hb_ref_k", "int", (1,)),
        ("hb_ref_scale", "W64.t", (2,)),
        ("hb_ref_bound", "W64.t", (3,)),
        ("hb_ref_cube", "W64.t * W64.t", (4, 5)),
        ("hb_ref_three", "W64.t * W64.t", (6, 7)),
    )
    for name, result_type, indices in operations:
        lines = [f"op {name} (mode : int) : {result_type} ="]
        for index, mode in enumerate(MODES):
            literals = [str(values[mode][column]) for column in indices]
            if result_type != "int":
                literals = [f"W64.of_int {literal}" for literal in literals]
            expression = literals[0] if len(literals) == 1 else f"({', '.join(literals)})"
            prefix = "if" if index == 0 else "else if"
            lines.append(f"  {prefix} mode = {mode} then {expression}")
        default = "0" if result_type == "int" else "W64.zero"
        if len(indices) == 2:
            default = "(W64.zero, W64.zero)"
        lines.append(f"  else {default}.")
        output.append("\n".join(lines))
    return "\n\n".join(output) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=REFERENCE,
                        help="C reference directory with include/ and src/ layout")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        result = generate(args.reference)
        args.output.write_text(result, encoding="utf-8")
    except (OSError, UnicodeError, ValueError, subprocess.CalledProcessError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
