#!/usr/bin/env python3
"""Generate exact integer interval data for the Hyperball tail constants.

Python is only a reproducible data generator. HyperballTailCertificateChecks
checks every seed and interval operation, and HyperballTailConstants proves
the analytic exponential and power interpretation in EasyCrypt.
"""

import argparse
from pathlib import Path


SCALE = 1 << 128
SQUARINGS = 32
COUNTS = (1538, 2306, 2818)
OUTPUT = Path(__file__).resolve().parents[1] / "theories/HyperballTailCertificate.ec"


def ceil_div(numerator, denominator):
    return (numerator + denominator - 1) // denominator


def interval_mul(left, right):
    return (left[0] * right[0] // SCALE,
            ceil_div(left[1] * right[1], SCALE))


def rational_interval(numerator, denominator):
    return (SCALE * numerator // denominator,
            ceil_div(SCALE * numerator, denominator))


def exponential_chain(numerator, denominator):
    """Enclose exp(-numerator/denominator) using 32 outward squarings."""
    small_denominator = denominator << SQUARINGS
    # 1-a/b <= exp(-a/b) <= b/(b+a); analytic proof is separate.
    seed = (SCALE * (small_denominator - numerator) // small_denominator,
            ceil_div(SCALE * small_denominator, small_denominator + numerator))
    chain = [seed]
    for _ in range(SQUARINGS):
        chain.append(interval_mul(chain[-1], chain[-1]))
    return chain


def power_chain(base, exponent):
    """Binary exponentiation; every prefix exponent is recorded and checked."""
    current = (SCALE, SCALE)
    prefix = 0
    chain = [(prefix, current)]
    for digit in bin(exponent)[2:]:
        current = interval_mul(current, current)
        prefix *= 2
        if digit == "1":
            current = interval_mul(current, base)
            prefix += 1
        chain.append((prefix, current))
    return chain


def interval_text(interval):
    return f"({interval[0]}, {interval[1]})"


def emit():
    lines = [
        "(* Generated by scripts/hyperball-tail-certificate.py. *)",
        "(* Data only: all arithmetic and analytic meaning are separately checked. *)",
        "require import AllCore IntDiv List.",
        "require import ExpIntervalSpec.",
        "",
        "type htc_power_state = int * ei_interval.",
        "",
        "op htc_rational_ok (D a b : int) (bound : ei_interval) : bool =",
        "  0 < D /\\ 0 <= a /\\ 0 < b /\\ 0 <= bound.`1 /\\",
        "  bound.`1*b <= D*a /\\ D*a <= bound.`2*b.",
        "",
        "op htc_seed_ok (D a b : int) (bound : ei_interval) : bool =",
        "  0 < D /\\ 0 < a < b /\\ 0 <= bound.`1 /\\",
        "  bound.`1*b <= D*(b-a) /\\ D*b <= bound.`2*(b+a).",
        "",
        "op htc_power_step_ok (D : int) (base : ei_interval)",
        "    (current next : htc_power_state) : bool =",
        "  0 <= current.`1 /\\",
        "  (next.`1=2*current.`1 \\/ next.`1=2*current.`1+1) /\\",
        "  next.`2 = (if next.`1=2*current.`1 then ei_mul D current.`2 current.`2",
        "    else ei_mul D (ei_mul D current.`2 current.`2) base).",
        "",
        "op htc_power_steps_check (D : int) (base : ei_interval)",
        "    (current : htc_power_state) (steps : htc_power_state list) : bool =",
        "  with steps = [] => true",
        "  with steps = next :: tail =>",
        "    htc_power_step_ok D base current next /\\",
        "    htc_power_steps_check D base next tail.",
        "",
        "op htc_power_check (D : int) (base : ei_interval)",
        "    (chain : htc_power_state list) : bool =",
        "  with chain = [] => false",
        "  with chain = first :: rest =>",
        "    first=(0,(D,D)) /\\ htc_power_steps_check D base first rest.",
        "",
        f"op htc_scale : int = {SCALE}.",
        "",
    ]
    for name, numerator, denominator in (("plus", 19, 160), ("minus", 45, 392)):
        chain = exponential_chain(numerator, denominator)
        lines.append(f"op [opaque] htc_exp_{name}_chain : ei_interval list = [")
        lines.append(";\n".join("  " + interval_text(value) for value in chain) + "].")
        lines.append(f"op [opaque] htc_exp_{name}_bound : ei_interval = {interval_text(chain[-1])}.")
        lines.append("")
    for name, numerator, denominator in (("plus", 3947, 4000), ("minus", 1963, 2000)):
        base = rational_interval(numerator, denominator)
        lines.append(f"op [opaque] htc_r{name}_bound : ei_interval = {interval_text(base)}.")
        lines.append("")
        for count in COUNTS:
            chain = power_chain(base, count)
            lines.append(f"op [opaque] htc_power_{name}_{count} : htc_power_state list = [")
            lines.append(";\n".join(
                f"  ({exponent}, {interval_text(value)})"
                for exponent, value in chain) + "].")
            lines.append(f"op [opaque] htc_power_{name}_bound_{count} : ei_interval = {interval_text(chain[-1][1])}.")
            lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="compare the exact generated bytes with the checked-in certificate")
    args = parser.parse_args()
    generated = emit().encode("utf-8")
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_bytes() != generated:
            raise SystemExit("FAIL: Hyperball tail certificate is not reproducible.")
        print("PASS: Hyperball tail certificate is byte-for-byte reproducible.")
    else:
        OUTPUT.write_bytes(generated)
        print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
