#!/usr/bin/env python3
"""Generate literal EasyCrypt constants from the pinned HAETAE C reference.

The Jasmin source and its EasyCrypt extraction are deliberately not inputs.
The generated word literals use signed representatives modulo 2^64 so that
their bits can be compared directly with the Jasmin extractor's literals.
"""

import argparse
import hashlib
from pathlib import Path
import re


REFERENCE = (
    Path(__file__).resolve().parents[2]
    / "HAETAE-1.2.0/reference_implementation/src/sampler.c"
)


def parse_array(source: str, name: str, bits: int, length: int) -> list[int]:
    declaration = re.search(
        rf"static const uint{bits}_t\s+{name}\s*\[[^]]+\]\s*=\s*\{{(.*?)\}};",
        source,
        re.S,
    )
    if declaration is None:
        raise ValueError(f"missing C reference array {name}")
    body = declaration.group(1)
    literal = rf"UINT{bits}_C\(\s*(0[xX][0-9a-fA-F]+|[0-9]+)\s*\)"
    values = [int(value, 0) for value in re.findall(literal, body)]
    residue = re.sub(literal, "", body).replace(",", "").strip()
    if residue or len(values) != length:
        raise ValueError(f"unexpected initializer for {name}: expected {length} values")
    if any(value < 0 or value >= 1 << bits for value in values):
        raise ValueError(f"out-of-range uint{bits}_t in {name}")
    return values


def function_body(source: str, name: str) -> str:
    declaration = re.search(
        rf"static uint64_t\s+{name}\s*\(.*?\)\s*\{{(.*?)^\}}",
        source,
        re.S | re.M,
    )
    if declaration is None:
        raise ValueError(f"missing C reference function {name}")
    return re.sub(r"/\*.*?\*/|//[^\n]*", "", declaration.group(1), flags=re.S)


def parse_coefficients(source: str) -> list[int]:
    body = function_body(source, "approx_exp")
    initial = r"int64_t\s+r\s*=\s*INT64_C\(\s*([0-9]+)\s*\)\s*;"
    step = (
        r"r\s*=\s*smulh48\(\s*r\s*,\s*xi\s*\)\s*([+-])"
        r"\s*INT64_C\(\s*([0-9]+)\s*\)\s*;"
    )
    first = re.search(initial, body)
    updates = re.findall(step, body)
    if first is None or len(updates) != 10:
        raise ValueError("approx_exp must contain its degree-10 C Horner evaluator")
    residue = re.sub(initial, "", body, count=1)
    residue = re.sub(step, "", residue)
    residue = re.sub(r"return\s*\(uint64_t\)\s*r\s*;", "", residue)
    if residue.strip():
        raise ValueError("unrecognized operation in C approx_exp")
    return [int(first.group(1))] + [
        int(value) * (1 if sign == "+" else -1) for sign, value in updates
    ]


def word_literal(value: int, bits: int) -> str:
    if value >= 1 << (bits - 1):
        value -= 1 << bits
    integer = str(value) if value >= 0 else f"({value})"
    return f"W{bits}.of_int {integer}"


def word_list(name: str, values: list[int], bits: int) -> str:
    items = [f"({word_literal(value, bits)})" for value in values]
    rows = ["; ".join(items[index : index + 3]) for index in range(0, len(items), 3)]
    return f"op {name} : W{bits}.t list =\n  [" + ";\n   ".join(rows) + "].\n"


def generate(reference: Path) -> str:
    data = reference.read_bytes()
    source = data.decode("utf-8")
    for name, expected in (("CDTLEN", 166), ("CDTHILEN", 76)):
        declaration = re.search(rf"^#define\s+{name}\s+(\d+)\s*$", source, re.M)
        if declaration is None or int(declaration.group(1)) != expected:
            raise ValueError(f"unexpected {name} in HAETAE-1.2.0 reference")
    hi = parse_array(source, "CDT83_HI", 32, 76)
    lo = parse_array(source, "CDT83_LO", 64, 166)
    tail_constants = re.findall(
        r"UINT64_C\(\s*(0[xX][0-9a-fA-F]+)\s*\)",
        function_body(source, "sample_gauss83"),
    )
    if not tail_constants or {int(value, 0) for value in tail_constants} != {524287}:
        raise ValueError("unexpected implicit high limb in C sample_gauss83")
    tail_hi = int(tail_constants[0], 0)
    if any(value > tail_hi for value in hi):
        raise ValueError("CDT83_HI contains a value wider than 19 bits")
    coefficients = parse_coefficients(source)
    last_threshold = (tail_hi << 64) + lo[-1]
    max_input = (1 << 83) - 1
    output = [
        "(* Generated by scripts/reference-constants.py from the pinned C reference.\n"
        "   Input: HAETAE-1.2.0/reference_implementation/src/sampler.c\n"
        f"   SHA-256: {hashlib.sha256(data).hexdigest()}\n"
        "   Word literals are signed representatives of the C unsigned bits. *)\n",
        "require import AllCore List.\nfrom Jasmin require import JModel_x86.\n"
        "require import BArray304 BArray1328.\n",
        word_list("reference_cdt83_hi_words", hi, 32),
        word_list("reference_cdt83_lo_words", lo, 64),
        "op reference_cdt83_hi : BArray304.t =\n"
        "  BArray304.of_list32 reference_cdt83_hi_words.\n"
        "op reference_cdt83_lo : BArray1328.t =\n"
        "  BArray1328.of_list64 reference_cdt83_lo_words.\n",
        f"op reference_cdt83_tail_hi : int = {tail_hi}.\n"
        f"op reference_cdt83_last_threshold : int = {last_threshold}.\n"
        f"op reference_cdt83_max_input : int = {max_input}.\n",
        "(* Coefficients appear in the C evaluator's descending-degree order. *)\n"
        "op reference_exp_coefficients : int list =\n  ["
        + "; ".join(str(value) for value in coefficients)
        + "].\n",
        "(* This evaluator specifies the reference's operations and coefficients;\n"
        "   it makes no assertion about a real exponential error bound. *)\n"
        "op reference_approx_exp (mul48 : W64.t -> W64.t -> W64.t)\n"
        "    (x : W64.t) : W64.t =\n"
        f"  let r0 = W64.of_int {coefficients[0]} in\n",
    ]
    for index, coefficient in enumerate(coefficients[1:], 1):
        sign = "+" if coefficient >= 0 else "-"
        expr = f"mul48 r{index - 1} x {sign} W64.of_int {abs(coefficient)}"
        if index < len(coefficients) - 1:
            output[-1] += f"  let r{index} = {expr} in\n"
        else:
            output[-1] += f"  {expr}.\n"
    return "\n".join(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=REFERENCE)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        result = generate(args.reference)
    except (OSError, UnicodeError, ValueError) as error:
        parser.error(str(error))
    args.output.write_text(result, encoding="utf-8")


if __name__ == "__main__":
    main()
